# Generated by Django 4.0.3 on 2022-03-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogWoman', '0003_stores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stores',
        ),
    ]
