# Generated by Django 4.0.3 on 2022-04-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogWoman', '0005_category_women_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='phones',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Известные телефоны', 'verbose_name_plural': 'Известные телефоны'},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Известные женщины', 'verbose_name_plural': 'Известные женщины'},
        ),
    ]
